version: 2.1

jobs:
  run-curl:
    docker:
      - image: circleci/node:15.4
    
    steps:
      - checkout
      - run: |
        curl --location --request POST 'http://f126c4922131.ngrok.io' \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "circleci-build-url": "'$CIRCLE_BUILD_URL'"
            }'

workflows:
  curl:
    jobs:
      - run-curl

